### ISSUE TITLE
Access Token returns null

### ISSUE THREAD

**Issue by KViray** [mazine/oauth2-client-kotlin#5]
> this is my code to generate a new token for the user

```
val tokenGenerator = oauth2Client().clientFlow(
                tokenEndpoint = URI("https://api-prod.corelogic.com/oauth/token"),
                clientID = "client_id",
                clientSecret = "client_secret",
                scope = listOf()
        )

        return mapToGenerateToken(GenerateTokenDTO(
                tokenGenerator.accessToken))

```

> but it returns the error

```
org.jetbrains.hub.oauth2.client.AuthException: null cannot be cast to non-null type kotlin.String
	at org.jetbrains.hub.oauth2.client.OAuth2Client.asAccessToken(OAuth2Client.kt:194)
	at org.jetbrains.hub.oauth2.client.OAuth2Client.access$asAccessToken(OAuth2Client.kt:6)
	at org.jetbrains.hub.oauth2.client.OAuth2Client$refreshableTokenSource$1.loadToken(OAuth2Client.kt:169)
	at org.jetbrains.hub.oauth2.client.AccessTokenSource.getAccessToken(AccessTokenSource.kt:12)
	at blockbuilder.services.CoreLogicService.generate(CoreLogicService.kt:48)
	at blockbuilder.controller.RequestTokenController.generateToken(RequestTokenController.kt:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
```

I tried testing the credentials on the website and it works

**Comment by mazine** [comment]
@KViray Can you try the same request from curl?
`curl -u 'clientId'  -XPOST https://api-prod.corelogic.com/oauth/token -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=client_credentials&scope='`

Does the endpoint respond with a proper JSON either erroneous or successful?

**Comment by KViray** [comment]
> ok I tried it on postman and this is the response:

`{
    "fault": {
        "faultstring": "Invalid client identifier {0}",
        "detail": {
            "errorcode": "oauth.v2.InvalidClientIdentifier"
        }
    }
}`

**Comment by KViray** [comment]
> but when I tried this

`curl -X POST --header "Authorization: Basic akNLNDV0a2toVTRQMzlIRHc5TDQwN2V2cHhNUTZHOVI6RUpkSEF3aVhlRVJFcUZmdw==" --header "Content-Type: application/x-www-form-urlencoded;charset=utf-8" "https://api-prod.corelogic.com/oauth/token?grant_type=client_credentials"`

> the response is success

`{
    "access_token": "7dFYkPQ0NHRsNBkMRkCpUpeAlNXx",
    "expires_in": "3599",
    "token_type": "Bearer"
}`

**Comment by KViray** [comment]
> but when I tried this:

`curl -X POST --header "Authorization: Basic SkFBaEcwZVVIN25kbGdkaEpmY1MwYmNjOUVubk14eTg6dlp2ckEyS1g4MW5XUHZCaQ==" --header "Content-Type: application/x-www-form-urlencoded;charset=utf-8" "https://api-prod.corelogic.com/oauth/token?grant_type=client_credentials"`

> the return is successful

`
{
"access_token": "zatKv9sGzMsNwJ4MRZDIkJ46PUMq",
"expires_in": "3599",
"token_type": "Bearer"
}
`

**Comment by KViray** [comment]
> ok I solved this issue by using khttp.post

`val response = khttp.post(url = "https://api-prod.corelogic.com/oauth/token",
                headers = mapOf("Authorization" to "Basic SkFBaEcwZVVIN25kbGdkaEpmY1MwYmNjOUVubk14eTg6dlp2ckEyS1g4MW5XUHZCaQ==",
                        "Content-type" to "application/x-www-form-urlencoded;charset=utf-8"),
                params = mapOf("grant_type" to "client_credentials"),
                data = mapOf("scope" to ""))`

> thank you for your time
